printf: printf.o
	gcc printf.o -o ../build/printf

another_printf: another_printf.o
	gcc another_printf.o -o ../build/another_printf

pythagorean_table: pythagorean_table.o
	gcc pythagorean_table.o -o ../build/pythagorean_table

format_table: format_table.o
	gcc format_table.o -o ../build/format_table

tab: tab.o
	gcc tab.o -o ../build/tab

another_printf.o: another_printf.c
	gcc -c another_printf.c

pythagorean_table.o: pythagorean_table.c
	gcc -c pythagorean_table.c

format_table.o: format_table.c
	gcc -c format_table.c

tab.o: tab.c
	gcc -c tab.c